
CREATE TABLE TBL_LOG_FTP_SIM (
  `ID_LOG_FTP` int(11) NOT NULL AUTO_INCREMENT,
  `USER_FTP` varchar(200) NOT NULL,
  `ACCION_SFTP` varchar(1000) NOT NULL,
  `DATE_SFTP` date DEFAULT curdate(),
  PRIMARY KEY (`ID_LOG_FTP`)
)	

